server:
  port: 11000
  servlet:
    context-path: /demo/nacos/consumer

# spring 配置
spring:
  # 项目配置
  application:
    name: @artifactId@
    version: @version@
#    description: @description@
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:13000
