server:
  port: 12010
  servlet:
    context-path: /demo/producer

# spring 配置
spring:
  # 项目配置
  application:
    name: demo-rocketmq-producer
    description: "rocketmq producer: 服务生产者"
  cloud:
    stream:
      bindings:
        # 自定义生产者组
        output-string:
          # 设置组名
          group: producer-group-rocketmq-string
          # 发送的topic
          destination: topic-rocketmq-string
          # 设置数据类型
          content-type: application/json
        output-object:
          group: producer-group-rocketmq-object
          destination: topic-rocketmq-object
          content-type: application/json
      rocketmq:
        binder:
          # RocketMQ NameServer 地址(老版本使用 namesrv-addr 配置项) <Default: 127.0.0.1:9876>
          name-server: 127.0.0.1:9876
          # 是否为 Producer 和 Consumer 开启消息轨迹功能 <Default: true>
          enable-msg-trace: true
          # 消息轨迹开启后存储的 topic 名称 <Default: RMQ_SYS_TRACE_TOPIC>
          customized-trace-topic: RMQ_SYS_TRACE_TOPIC
        bindings:
          output-string:
            producer:
              group: producer-group-rocketmq-string
          output-object:
            producer:
              group: producer-group-rocketmq-object