server:
  port: 11000
  servlet:
    context-path: /demo/consumer

# spring 配置
spring:
  # 项目配置
  application:
    name: demo-dubbo-consumer
    version: @version@
  #    description: @description@
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:13000

dubbo:
  cloud:
    subscribed-services: demo-dubbo-consumer
  protocols:
    dubbo:
      port: -1
  registry:
    address: nacos://127.0.0.1:13000
    protocol: nacos
    port: 13000
  consumer:
    check: false