server:
  port: 11000
  servlet:
    context-path: /demo/consumer

# spring 配置
spring:
  # 项目配置
  application:
    name: demo-dubbo-consumer
    version: @version@
  #    description: @description@
  cloud:
    stream:
      bindings:
        # 自定义消费组
        input-string:
          # 设置组名
          group: consumer-group-rocketmq-string
          # 接收的topic
          destination: topic-rocketmq-string
          # 设置消息类型
          content-type: application/json
        input-object:
          group: consumer-group-rocketmq-object
          destination: topic-rocketmq-object
          content-type: application/json
      rocketmq:
        binder:
          # RocketMQ NameServer 地址(老版本使用 namesrv-addr 配置项) <Default: 127.0.0.1:9876>
          name-server: 127.0.0.1:9876
          # 是否为 Producer 和 Consumer 开启消息轨迹功能 <Default: true>
          enable-msg-trace: true
          # 消息轨迹开启后存储的 topic 名称 <Default: RMQ_SYS_TRACE_TOPIC>
          customized-trace-topic: RMQ_SYS_TRACE_TOPIC
        bindings:
          input-string:
            consumer:
#              orderly: true
              tags: getHello
          input-object:
            consumer:
              orderly: true
              tags: postHello