server:
  port: 12010
  servlet:
    context-path: /demo/sentinel/producer

# spring 配置
spring:
  # 项目配置
  application:
    name: @artifactId@
    version: @version@
  #    description: @description@
  cloud:
    #    nacos:
    #      discovery:
    #        server-addr: 127.0.0.1:13000
    sentinel:
      transport:
#        port: 8080
        dashboard: localhost:8080